idf_component_register(
    SRCS
        "source/uwb_port_spi.c"
        "source/uwb_port_gpio.c"
        "source/uwb_port_irq.c"
        "source/uwb_port_time.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "../uwb_poc/include"
    REQUIRES
        esp_driver_gpio
        esp_driver_spi
        esp_timer
        freertos
        log
    PRIV_REQUIRES
        uwb_poc
)
